### ISSUE TITLE
Update to new Ubuntu LTS 22.04

### ISSUE THREAD

**Issue by langchr86** [scs/jumpstart-vm#5]
Tasks:
* Update Vagrant & Ansible etc.
* Update documentation etc.
* others?

**Comment by klaegera** [comment]
Provisioning with Hyper-V on 22.04 for Jumpstart tomorrow:

<br />

```
TASK [Install DKMS and virtualbox additions] ***********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'virtualbox-guest-dkms' is available"}
```
-> commented out `- include_tasks: tasks/virtualbox_additions.yml` in `playbook.yml`

<br />

```
TASK [Install build tools] *****************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'python' is available"}
```
-> commented out `- python` in `buildtools.yml`

<br />

Issues connecting from host via SSH:
`sudo ufw disable`
